default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *default
  database: auth_service_test

production:
  <<: *default
  database: auth_service_production
  username: auth_service
  password: <%= ENV['AUTH_SERVICE_DATABASE_PASSWORD'] %>
